[package]
name = "h3o-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geojson = "0.24.1"
h3o = { version = "0.6", features = ["geo"] }
webbrowser = "0.8.12"
